### ISSUE TITLE
ライセンスの文面が不完全

### ISSUE THREAD

**Issue by kaznak** [dai-motoki/zoltraak#1]
現状のライセンスの文面は不完全です。
https://github.com/dai-motoki/zoltraak/blob/9a773159882d3866f302f8128bc19d89d97652a6/LICENSE

以下の箇所を修正する必要があります

- `<one line to give the program's name and a brief idea of what it does.>`
- `Copyright (C) <year>  <name of author>`
- `<program>  Copyright (C) <year>  <name of author>`

**Comment by dai-motoki** [comment]
ありがとうございます。こちらgithubのものをそのまま利用しています。

**Comment by dai-motoki** [comment]
こちらアップデート完了しました。
